package edgar

var MenuCategories = []MenuCategory{
	{
		Name: "Cover",
		Keys: []string{"cover"},
	},
	{
		Name: "Financial statements",
		Keys: []string{"financial", "statement"},
	},
	{
		Name: "Notes to Financial statements",
		Keys: []string{"note", "financial", "statement"},
	},
	{
		Name: "Notes Tables",
		Keys: []string{"table"},
	},
	{
		Name: "Notes Details",
		Keys: []string{"detail"},
	},
	{
		Name: "Accounting Policies",
		Keys: []string{"polic"},
	},
}

var CategoryDocs = map[string][]Document{
	"Cover": {
		{
			Category:   "Cover",
			Name:       "Cover Page",
			Type:       "Entity Info",
			Keys:       []string{"DOCUMENT", "ENTITY"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Cover",
			Name:       "Cover Page",
			Type:       "Entity Info",
			Keys:       []string{"COVER"},
			NotKeys:    []string{},
			IsRequired: false,
		},
	},
	"Financial statements": {
		{
			Category:   "Financial statements",
			Name:       "Balance sheet",
			Type:       "Assets",
			Keys:       []string{"BALANCE SHEET"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Financial statements",
			Name:       "Balance sheet",
			Type:       "Assets",
			Keys:       []string{"FINANCIAL POSITION"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Financial statements",
			Name:       "Operations statement",
			Type:       "Operations",
			Keys:       []string{"OPERATIONS"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Financial statements",
			Name:       "Income statement",
			Type:       "Income",
			Keys:       []string{"INCOME"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Financial statements",
			Name:       "Income statement",
			Type:       "Income",
			Keys:       []string{"INCOME", "EARNINGS"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Financial statements",
			Name:       "Cash flow statement",
			Type:       "Cash Flow",
			Keys:       []string{"CASH FLOWS"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Financial statements",
			Name:       "Parenthetical statement",
			Type:       "Parenthetical",
			Keys:       []string{"PARENTHETICAL"},
			NotKeys:    []string{},
			IsRequired: false,
		},
	},
	"Notes to Financial statements": {
		{
			Category:   "Notes to Financial statements",
			Name:       "Notes - Notes on EPS",
			Type:       "Notes on EPS",
			Keys:       []string{"EARNINGS", "SHARE"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Notes to Financial statements",
			Name:       "Notes - Notes on Equity",
			Type:       "Notes on Equity",
			Keys:       []string{"SHAREHOLDER", "EQUITY"},
			NotKeys:    []string{},
			IsRequired: false,
		},
		{
			Category:   "Notes to Financial statements",
			Name:       "Notes - Notes on Debt",
			Type:       "Notes on Debt",
			Keys:       []string{"DEBT"},
			NotKeys:    []string{},
			IsRequired: false,
		},
	},
	"Notes Tables": {{
		Category:   "Notes Tables",
		Name:       "Notes - Notes on EPS",
		Type:       "Tables",
		Keys:       []string{"(TABLES)"},
		NotKeys:    []string{},
		IsRequired: false,
	},
		{
			Category:   "Notes Tables",
			Name:       "Accounting Policies (Tables)",
			Type:       "PoliciesTable",
			Keys:       []string{"Accounting Policies (Tables)"},
			NotKeys:    []string{""},
			IsRequired: false,
		},
	},
	"Notes Details": {
		{
			Category:   "}Notes Details",
			Name:       "Notes Details",
			Type:       "Details",
			Keys:       []string{"(DETAILS)", "(DETAIL)"},
			NotKeys:    []string{""},
			IsRequired: false,
		},
	},

	"Accounting Policies": {
		{
			Category:   "Accounting Policies",
			Name:       "Accounting Policies",
			Type:       "Policies",
			Keys:       []string{"(POLICIES)"},
			NotKeys:    []string{""},
			IsRequired: false,
		},
	},
}

var RequiredDocs = []Document{
	{
		Category:   "",
		Name:       "Operations",
		Type:       "Operations",
		Keys:       []string{},
		NotKeys:    []string{},
		IsRequired: true,
	},
	{
		Name:       "Income",
		Type:       "Income",
		IsRequired: true,
	},
	{
		Name:       "Assets",
		Type:       "Assets",
		IsRequired: true,
	},
	{
		Name:       "Cash Flow",
		Type:       "Cash Flow",
		IsRequired: true,
	},
	{
		Name:       "Entity Info",
		Type:       "Entity Info",
		IsRequired: true,
	},
}
var RestrictedTags = map[string]bool{
	// "Namespace Prefix:": false,
	// "Data Type:":        false,
}

// A Map of XBRL tags to financial data type
// This map contains the corresponding GAAP tag and a version of the tag
// without the GAAP keyword in case the company has only file non-gaap
var XBRLTags = map[string]string{
	// //Balance Sheet info
	// "defref_us-gaap_StockholdersEquity":                            "Total Shareholder Equity",
	// "StockholdersEquity":                                           "Total Shareholder Equity",
	// "defref_us-gaap_RetainedEarningsAccumulatedDeficit":            "Retained Earnings",
	// "RetainedEarningsAccumulatedDeficit":                           "Retained Earnings",
	// "defref_us-gaap_LiabilitiesCurrent":                            "Current Liabilities",
	// "LiabilitiesCurrent":                                           "Current Liabilities",
	// "defref_us-gaap_AssetsCurrent":                                 "Current Assets",
	// "AssetsCurrent":                                                "Current Assets",
	// "defref_us-gaap_Assets":                                        "Total Assets",
	// "Assets":                                                       "Total Assets",
	// "defref_us-gaap_Liabilities":                                   "Total Liabilities",
	// "Liabilities":                                                  "Total Liabilities",
	// "defref_us-gaap_CashAndCashEquivalentsAtCarryingValue":         "Cash",
	// "CashAndCashEquivalentsAtCarryingValue":                        "Cash",
	// "defref_us-gaap_Goodwill":                                      "Goodwill",
	// "Goodwill":                                                     "Goodwill",
	// "defref_us-gaap_IntangibleAssetsNetExcludingGoodwill":          "Intangibles",
	// "IntangibleAssetsNetExcludingGoodwill":                         "Intangibles",
	// "defref_us-gaap_LongTermDebtNoncurrent":                        "Long-Term debt",
	// "LongTermDebtNoncurrent":                                       "Long-Term debt",
	// "defref_us-gaap_LongTermDebtAndCapitalLeaseObligations":        "Long-Term debt",
	// "LongTermDebtAndCapitalLeaseObligations":                       "Long-Term debt",
	// "defref_us-gaap_ShortTermBorrowings":                           "Short-Term debt",
	// "ShortTermBorrowings":                                          "Short-Term debt",
	// "defref_us-gaap_DebtCurrent":                                   "Short-Term debt",
	// "DebtCurrent":                                                  "Short-Term debt",
	// "defref_us-gaap_LongTermDebtAndCapitalLeaseObligationsCurrent": "Short-Term debt",
	// "LongTermDebtAndCapitalLeaseObligationsCurrent":                "Short-Term debt",
	// "defref_us-gaap_DeferredRevenueCurrent":                        "Deferred revenue",
	// "DeferredRevenueCurrent":                                       "Deferred revenue",
	// "defref_us-gaap_RetainedEarningsAccumulatedDeficitAndAccumulatedOtherComprehensiveIncomeLossNetOfTax": "Retained Earnings",
	// "RetainedEarningsAccumulatedDeficitAndAccumulatedOtherComprehensiveIncomeLossNetOfTax":                "Retained Earnings",

	// //Operations Sheet info
	// "defref_us-gaap_SalesRevenueNet": "Revenue",
	// "SalesRevenueNet":                "Revenue",
	// "defref_us-gaap_Revenues":        "Revenue",
	// "Revenues":                       "Revenue",
	// "defref_us-gaap_RevenueFromContractWithCustomerExcludingAssessedTax":            "Revenue",
	// "RevenueFromContractWithCustomerExcludingAssessedTax":                           "Revenue",
	// "defref_us-gaap_CostOfRevenue":                                                  "Cost Of Revenue",
	// "defref_us-gaap_CostOfGoodsAndServicesSold":                                     "Cost Of Revenue",
	// "CostOfGoodsAndServicesSold":                                                    "Cost Of Revenue",
	// "defref_us-gaap_CostOfPurchasedOilAndGas":                                       "Cost Of Revenue",
	// "CostOfPurchasedOilAndGas":                                                      "Cost Of Revenue",
	// "defref_us-gaap_CostOfGoodsSold":                                                "Cost Of Revenue",
	// "CostOfGoodsSold":                                                               "Cost Of Revenue",
	// "defref_us-gaap_CostOfGoodsSoldExcludingAmortizationOfAcquiredIntangibleAssets": "Cost Of Revenue",
	// "CostOfGoodsSoldExcludingAmortizationOfAcquiredIntangibleAssets":                "Cost Of Revenue",
	// "defref_us-gaap_GrossProfit":                                                    "Gross Margin",
	// "GrossProfit":                                                                   "Gross Margin",
	// "defref_us-gaap_OperatingExpenses":                                              "Operational Expense",
	// "OperatingExpenses":                                                             "Operational Expense",
	// "defref_us-gaap_CostsAndExpenses":                                               "Operational Expense",
	// "CostsAndExpenses":                                                              "Operational Expense",
	// "defref_us-gaap_OtherCostAndExpenseOperating":                                   "Operational Expense",
	// "OtherCostAndExpenseOperating":                                                  "Operational Expense",
	// "defref_us-gaap_OperatingIncomeLoss":                                            "Operational Income",
	// "OperatingIncomeLoss":                                                           "Operational Income",
	// "defref_us-gaap_IncomeLossIncludingPortionAttributableToNoncontrollingInterest": "Operational Income",
	// "defref_us-gaap_IncomeLossFromContinuingOperationsIncludingPortionAttributableToNoncontrollingInterest":                      "Operational Income",
	// "IncomeLossFromContinuingOperationsIncludingPortionAttributableToNoncontrollingInterest":                                     "Operational Income",
	// "IncomeLossIncludingPortionAttributableToNoncontrollingInterest":                                                             "Operational Income",
	// "defref_us-gaap_IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments": "Operational Income",
	// "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments":                "Operational Income",
	// "defref_us-gaap_NetIncomeLoss": "Net Income",
	// "NetIncomeLoss":                "Net Income",
	// "defref_us-gaap_ProfitLoss":    "Net Income",
	// "ProfitLoss":                   "Net Income",
	// "defref_us-gaap_NetIncomeLossAvailableToCommonStockholdersBasic": "Net Income",
	// "NetIncomeLossAvailableToCommonStockholdersBasic":                "Net Income",
	// "defref_us-gaap_WeightedAverageNumberOfDilutedSharesOutstanding": "Weighted Average Share Count",
	// "WeightedAverageNumberOfDilutedSharesOutstanding":                "Weighted Average Share Count",
	// "defref_us-gaap_CommonStockDividendsPerShareDeclared":            "Dividend Per Share",
	// "CommonStockDividendsPerShareDeclared":                           "Dividend Per Share",

	// "defref_us-gaap_IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest": "Operational Income",
	// "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest":                "Operational Income",

	// //Cash Flow Sheet info
	// "defref_us-gaap_NetCashProvidedByUsedInOperatingActivities":                     "Operating Cash Flow",
	// "NetCashProvidedByUsedInOperatingActivities":                                    "Operating Cash Flow",
	// "defref_us-gaap_NetCashProvidedByUsedInOperatingActivitiesContinuingOperations": "Operating Cash Flow",
	// "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations":                "Operating Cash Flow",
	// "defref_us-gaap_PaymentsToAcquirePropertyPlantAndEquipment":                     "Capital Expenditure",
	// "PaymentsToAcquirePropertyPlantAndEquipment":                                    "Capital Expenditure",
	// "defref_us-gaap_PaymentsToAcquireProductiveAssets":                              "Capital Expenditure",
	// "PaymentsToAcquireProductiveAssets":                                             "Capital Expenditure",
	// "defref_us-gaap_CapitalExpendituresAndInvestments":                              "Capital Expenditure",
	// "CapitalExpendituresAndInvestments":                                             "Capital Expenditure",
	// "defref_us-gaap_PaymentsOfDividends":                                            "Dividends paid",
	// "PaymentsOfDividends":                                                           "Dividends paid",
	// "defref_us-gaap_PaymentsOfDividendsCommonStock":                                 "Dividends paid",
	// "PaymentsOfDividendsCommonStock":                                                "Dividends paid",
	// "defref_us-gaap_InterestPaidNet":                                                "Interest paid",
	// "InterestPaidNet":                                                               "Interest paid",
	// "defref_us-gaap_InterestAndDebtExpense":                                         "Interest paid",
	// "InterestAndDebtExpense":                                                        "Interest paid",
	// "defref_us-gaap_InterestIncomeExpenseNet":                                       "Interest paid",
	// "InterestIncomeExpenseNet":                                                      "Interest paid",
	// //Entity sheet information
	// "defref_dei_EntityCommonStockSharesOutstanding": "Shares Outstanding",
	// "EntityCommonStockSharesOutstanding":            "Shares Outstanding",
}
